 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Paula Emad
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_PinConfig= 
{
  PORT_A, PIN_0, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin A0*/
  PORT_A, PIN_1, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_1, STD_OFF, STD_OFF,  /*pin A1*/
  PORT_A, PIN_2, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin A2*/
  PORT_A, PIN_3, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin A3*/
  PORT_A, PIN_4, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin A4*/
  PORT_A, PIN_5, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin A5*/
  PORT_A, PIN_6, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin A6*/
  PORT_A, PIN_7, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin A7*/
  
  PORT_B, PIN_0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_6, STD_OFF, STD_OFF,  /*pin B0*/
  PORT_B, PIN_1, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin B1*/
  PORT_B, PIN_2, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_6, STD_OFF, STD_OFF,  /*pin B2*/
  PORT_B, PIN_3, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW,  	PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin B3*/
  PORT_B, PIN_4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_6, STD_OFF, STD_OFF,  /*pin B4*/
  PORT_B, PIN_5, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_AIN, STD_OFF, STD_OFF,  /*pin B5*/
  PORT_B, PIN_6, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin B6*/
  PORT_B, PIN_7, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin B7*/
  
  PORT_C, PIN_0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin C0*/
  PORT_C, PIN_1, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin C1*/
  PORT_C, PIN_2, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin C2*/
  PORT_C, PIN_3, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin C3*/
  PORT_C, PIN_4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin C4*/
  PORT_C, PIN_5, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin C5*/
  PORT_C, PIN_6, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin C6*/
  PORT_C, PIN_7, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin C7*/
  
  PORT_D, PIN_0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin D0*/
  PORT_D, PIN_1, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin D1*/
  PORT_D, PIN_2, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin D2*/
  PORT_D, PIN_3, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin D3*/
  PORT_D, PIN_4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin D4*/
  PORT_D, PIN_5, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin D5*/
  PORT_D, PIN_6, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin D6*/
  PORT_D, PIN_7, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin D7*/
  
  PORT_E, PIN_0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin E0*/
  PORT_E, PIN_1, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin E1*/
  PORT_E, PIN_2, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin E2*/
  PORT_E, PIN_3, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_AIN, STD_OFF, STD_OFF,  /*pin E3*/
  PORT_E, PIN_4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_7, STD_OFF, STD_OFF,  /*pin E4*/
  PORT_E, PIN_5, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_7, STD_OFF, STD_OFF,  /*pin E5*/
  
  PORT_F, PIN_0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_HIGH,  PORT_PIN_MODE_6, STD_OFF, STD_OFF,  /*pin F0*/
  PORT_F, PIN_1, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin F1*/
  PORT_F, PIN_2, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin F2*/
  PORT_F, PIN_3, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF,  /*pin F3*/
  PORT_F, PIN_4, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_0, STD_OFF, STD_OFF  /*pin F4*/
				         };