#include "Icu.h"

const Icu_ConfigType Icu_Config = {
  0,ICU_RISING_EDGE,ICU_MODE_TIMESTAMP,ICU_PERIOD_TIME,ICU_LINEAR_BUFFER,
  2,ICU_RISING_EDGE,ICU_MODE_EDGE_COUNTER,ICU_PERIOD_TIME,ICU_LINEAR_BUFFER,
  4,ICU_RISING_EDGE,ICU_MODE_TIMESTAMP,ICU_PERIOD_TIME,ICU_LINEAR_BUFFER
};